Dm 18 announcements
cepdnaclk/dental-patient-management-system pull request #18
Opened 2023-06-20 09:30 UTC by JayathriRanasinghe

Announcements, side navbar updated

2023-06-20 09:38 UTC, JayathriRanasinghe commented
fogot to commit the laravelcollective package update in composer.json before the sidebar commit. I think that is the reason for the failure.

2023-06-20 09:56 UTC, NuwanJ requested changes

2023-06-20 09:56 UTC, NuwanJ commented on routes/web.php
> +    })->name('component.index');
These 3 lines were not required for us

2023-06-20 10:02 UTC, NuwanJ commented
I have reviewed the code and nice work! 👌🏼 
Here in the thread, you can find a small comment. Can you fix it also?

2023-06-24 13:50 UTC, NuwanJ approved these changes

2023-06-24 13:54 UTC, merged